**Basic data structures and data types**


In [2]:
age = 32
print(f"i am a very ressilient man aged {age} years old.")


i am a very ressilient man aged 32 years old.


In [3]:
print("i am {} years old".format(age))

i am 32 years old


In [4]:
print("i am " + str(age) +  " years old. ")

i am 32 years old. 


In [6]:
type(1.0)

float

In [7]:
2**5

32

In [8]:
4%2

0

In [9]:
5%2

1

In [10]:
(2+2)*(5+5)

40

In [11]:
y= 2
x = 5
z = 7

In [12]:
y+x+z


14

In [13]:
y*x*z

70

In [14]:
"i dont like that"

'i dont like that'

In [15]:
"i don't like that"

"i don't like that"

In [16]:
print("hello")

hello


In [17]:
"hello"

'hello'

In [18]:
#sting interpolation
print("My name is {}" .format('kabira'))


My name is kabira


In [19]:
print("My name is {}, my number is {} " .format('kabira','7'))

My name is kabira, my number is 7 


In [20]:
print("First: {x} Second: {y}".format(x='XXX',y='YYY'))

First: XXX Second: YYY


In [21]:
[1,2,3,4]

[1, 2, 3, 4]

In [22]:
['a','b','c']

['a', 'b', 'c']

In [23]:
mylist = ['a','b','c']
mylist

['a', 'b', 'c']

In [24]:
#list indexing
mylist[0]

'a'

In [25]:
mylist[-1]

'c'

In [26]:
mylist[2]

'c'

In [27]:
mylist[0] = 'NEW'

In [28]:
mylist

['NEW', 'b', 'c']

In [29]:
mylist.append('d')
mylist

['NEW', 'b', 'c', 'd']

In [30]:
list1=[1,2, [100,200]]
list1

[1, 2, [100, 200]]

In [31]:
mylist

['NEW', 'b', 'c', 'd']

In [32]:
list1[2]

[100, 200]

In [33]:
list1[2][1]

200

In [34]:
#dictionaries also known as ash tables in other languanges
#key value pairs for storing data that can be accessed easily
d = {'key1':'value1','key2':'value2','key3':'value3'}

In [35]:
d['key1']

'value1'

In [36]:
d['key2']

'value2'

In [37]:
#booleans
True 

True

In [38]:
False

False

In [39]:
#Truthy and Falsy
0 and 1

0

In [40]:
#tuples and sets 
t = (1,2,3,4) #cannot be changed
t[0]

1

In [41]:
#sets looks like dictonary but no key value pairs
#its unordered collection of unique elements
{1,2,3,}

{1, 2, 3}

In [42]:
{1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,77,7}

{1, 2, 3, 7, 77}

In [43]:
def my_func():
    print('hello')
    

In [44]:
my_func()

hello


In [45]:
def my_func(name):
    print('hello ' +name)

In [46]:
my_func('Kabira')

hello Kabira


In [47]:
def my_func(name='NO NAME'):
    print('hello ' +name)

In [48]:
my_func()

hello NO NAME


In [49]:
def my_func(name):
    '''
    This prints out the user name!
    '''
    print('hello ' +name)

In [50]:
my_func('Kabira')


hello Kabira


In [51]:
def square(x):
     return x**2
   

In [52]:
results = square(2)

In [53]:
results

4

In [54]:
type(results)

int

In [55]:
def square(x):
    print(x**2)
results

4

In [57]:
results

4

In [58]:
results

4

In [59]:
#lambda expressions
def times_two(var):
    return var*2
times_two(7)


14

In [60]:
times_two(10)

20

In [62]:
lambda var: var*2

<function __main__.<lambda>(var)>

In [63]:
lambda var: var*2



<function __main__.<lambda>(var)>

In [64]:
st ='hello my name is kabira'
st.lower()

'hello my name is kabira'

In [65]:
st ='hello my name is kabira'
st.upper()

'HELLO MY NAME IS KABIRA'

In [66]:
st ='hello my name is kabira'
st.split()

['hello', 'my', 'name', 'is', 'kabira']

In [67]:
tweet = 'Hello #sports'

In [68]:
tweet.split('#')[-1]
['Hello', '#sports']

['Hello', '#sports']

In [69]:
tweet.split('#')[-1]

'sports'

In [70]:
tweet.split('#')

['Hello ', 'sports']

In [71]:
tweet.split('#')[0]

'Hello '

In [72]:
tweet.split('#')[1]

'sports'

In [73]:
d ={'k1':'v1','k2':'v2'}

In [74]:
d.keys()

dict_keys(['k1', 'k2'])

In [75]:
d.items()

dict_items([('k1', 'v1'), ('k2', 'v2')])

In [76]:
mylist = [1,2,2,3,4,5]

In [77]:
last = mylist.pop()#removes the last itme in a list
mylist

[1, 2, 2, 3, 4]

In [78]:
mylist

[1, 2, 2, 3, 4]

In [79]:
mylist.pop(0)#removes the parsed index in this case 0
mylist

[2, 2, 3, 4]

In [80]:
'x' in [1,2,3,2]#in operator

False

In [81]:
1 in [1,2,2,3]

True

In [82]:
#numpy arrays
import numpy as np

In [148]:
mylist =[1,2,3]

In [149]:
type(mylist)

list

In [150]:
np.array (mylist)

array([1, 2, 3])

In [151]:
myarr = np.array(mylist)
myarr

array([1, 2, 3])

In [152]:
type(myarr)

numpy.ndarray

In [154]:
my_matrix =[[1,2,3],[4,5,6],[7,8,9]]

In [155]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [156]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [158]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [159]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [160]:
np.arange(0,101,20)

array([  0,  20,  40,  60,  80, 100])

In [162]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [164]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [165]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [168]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [169]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [171]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [174]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [175]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [176]:
len(np.linspace(0,10,21))

21

In [177]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [185]:
#random distributions of data
np.random.rand(1)

array([0.16224279])

In [186]:
np.random.rand(5,6)

array([[0.84995871, 0.84844715, 0.34852811, 0.41665468, 0.2071122 ,
        0.11231687],
       [0.88452701, 0.17655952, 0.4006297 , 0.16557441, 0.76113113,
        0.99869262],
       [0.79052143, 0.11740458, 0.57955532, 0.40775564, 0.49161312,
        0.63011318],
       [0.2411023 , 0.82956777, 0.87884707, 0.21147161, 0.13771708,
        0.23156978],
       [0.36602161, 0.98439511, 0.74237663, 0.62468456, 0.82916916,
        0.21376728]])

In [187]:
np.random.rand(5,2)

array([[0.12339873, 0.65211562],
       [0.35115867, 0.11176469],
       [0.97878769, 0.5407253 ],
       [0.31785547, 0.12836575],
       [0.13421387, 0.46138485]])

In [188]:
np.random.randn(10)#mean = 0 variance = 1

array([-0.08002477, -0.16693597, -0.4213563 , -0.49444069,  0.00549009,
       -1.03620343, -0.27570911, -1.10791241, -0.96121711, -0.15633394])

In [189]:
np.random.randn(2,3)

array([[-0.75242076, -0.15439456,  1.03710366],
       [ 0.66083558,  0.13095899,  2.5653925 ]])

In [ ]:
np.random.randint(0,101,5)#integers

array([71, 96, 73, 50, 83], dtype=int32)

In [192]:
np.random.randint(0,101,20)

array([30, 14, 84, 32, 68, 96, 15, 60,  6, 67, 54, 58, 76, 63, 97, 35, 35,
       46, 16, 56], dtype=int32)

In [ ]:
np.random.seed(42)#sets random numbers,42 is just arbitrary
np.random.rand(4)#must be in same cell to get same random numbers

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [195]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [196]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [197]:
ranarr = np.random.randint(0,101,10)

In [198]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52], dtype=int32)

In [199]:
ranarr.max()

np.int32(99)

In [200]:
ranarr.min()

np.int32(2)

In [201]:
ranarr.argmax

<function ndarray.argmax>

In [202]:
ranarr.argmin()

np.int64(7)

In [203]:
ranarr.dtype

dtype('int32')

In [204]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [205]:
arr.shape

(25,)

In [206]:
arr = arr.reshape(5,5)

In [207]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [208]:
arr.shape

(5, 5)

In [209]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [212]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [213]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [216]:
#indexing and selection in numpy
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [218]:
arr[8]

np.int64(8)

In [219]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [220]:
arr[1:5]

array([1, 2, 3, 4])

In [221]:
arr[:5]

array([0, 1, 2, 3, 4])

In [222]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [223]:
#broadcasting
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [226]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [228]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [230]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [233]:
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99])

In [234]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100# used when you what to keep the original array(use .copy)
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr# original array not bchanged

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [240]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [241]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [242]:
arr_2d.shape

(3, 3)

In [243]:
arr_2d[0]

array([ 5, 10, 15])

In [244]:
arr_2d[2]

array([35, 40, 45])

In [245]:
arr_2d[1,1]

np.int64(25)

In [246]:
arr_2d[0,2]

np.int64(15)

In [247]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [248]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [249]:
#conditional selection
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [250]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [251]:
bool_arr = arr>4

In [252]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [254]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [256]:
arr[arr >4]

array([ 5,  6,  7,  8,  9, 10])

In [258]:
arr =np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [259]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [260]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [261]:
arr +arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [262]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [263]:
arr/arr

C:\Users\USER\AppData\Local\Temp\ipykernel_18440\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [264]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [265]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [266]:
1/arr

C:\Users\USER\AppData\Local\Temp\ipykernel_18440\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [267]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [268]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [269]:
np.log(arr)

C:\Users\USER\AppData\Local\Temp\ipykernel_18440\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [270]:
arr.sum()

np.int64(45)

In [271]:
arr.mean()

np.float64(4.5)

In [272]:
arr.max()

np.int64(9)

In [273]:
arr.var()

np.float64(8.25)

In [275]:
arr.std()

np.float64(2.8722813232690143)

In [280]:
arr2d=np.arange(0,25).reshape(5,5)

In [281]:
arr2d.shape

(5, 5)

In [282]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [283]:
arr2d.shape

(5, 5)

In [285]:
arr2d.sum()

np.int64(300)

In [324]:
arr2d.sum(axis=0)#sum across the rows-vertical**
#🔹 Now to the Axis Logic
#👉 arr2d.sum(axis=0)
#Means: sum along axis 0 (the row axis)

#NumPy "compresses" axis 0 → it sums vertically down each column

#Result: 1 row of column totals

array([50, 55, 60, 65, 70])

In [325]:
arr2d.sum(axis=1)#sum across the columns-horizontal**
#👉 arr2d.sum(axis=1)
#Means: sum along axis 1 (the column axis)

#NumPy "compresses" axis 1 → it sums horizontally across each row

#Result: 1 column of row totals

array([ 10,  35,  60,  85, 110])

In [ ]:
#🧠 The Core Idea Behind axis in NumPy
#In NumPy, the axis number refers to the dimension you want to operate along — i.e., the dimension that will collapse (or be reduced) by the operation like sum, mean, max, etc.

#👇 In a 2D Array (shape = (rows, columns)):
#axis=0 means:
#→ collapse rows → perform operation down each column

#axis=1 means:
#→ collapse columns → perform operation across each row

#🔄 Think of Axes Like Coordinates:
#In a 2D grid:

#Axis 0 = move down (along rows) → vertical

#Axis 1 = move right (along columns) → horizontal

#So:

#Axis 0 → vertical → rows → like the Y-axis

#Axis 1 → horizontal → columns → like the X-axis


#✅ Summary:
#Axis	What it Means	Collapse Which Axis?	Direction	Operation Happens
#0	Operate down columns	Collapsing rows	Vertical ↓	Per column
#1	Operate across rows	Collapsing columns	Horizontal →	Per row



**Pandas**

## Pandas Series Section

In [288]:
#pandas series 
import pandas as pd

In [293]:
pd.Series

pandas.core.series.Series

In [292]:
myindex = ['USA','Canada','Mexico']

In [291]:
mydata = [1776,1867,1821]

In [294]:
mySer = pd.Series(data=mydata)

In [295]:
mySer

0    1776
1    1867
2    1821
dtype: int64

In [296]:
type(mySer)

pandas.core.series.Series

In [297]:
mySer = pd.Series(data=mydata,index=myindex)

In [298]:
mySer

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [299]:
mySer[0]

C:\Users\USER\AppData\Local\Temp\ipykernel_18440\4088936655.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mySer[0]


np.int64(1776)

In [300]:
mySer['USA']

np.int64(1776)

In [301]:
ages = {'Sam':5,'Frank':10,'Spike':7}

In [302]:
pd.Series(ages)

Sam       5
Frank    10
Spike     7
dtype: int64

In [303]:
# Imaginary Sales Data for 1st and 2nd Quarters for Global Company
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [304]:
sales_q1 = pd.Series(q1)

In [305]:
sales_q2 = pd.Series(q2)

In [306]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [308]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [ ]:
sales_q1['Japan']#use name keys over index for data to be readable by other stakeholders

np.int64(80)

In [310]:
sales_q1[0]

C:\Users\USER\AppData\Local\Temp\ipykernel_18440\92651501.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  sales_q1[0]


np.int64(80)

In [311]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [312]:
#let perfor broadcasted operation
np.array([1,2])*2

array([2, 4])

In [313]:
sales_q1*2

Japan    160
China    900
India    400
USA      500
dtype: int64

In [314]:
sales_q1/100

Japan    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64

In [315]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [316]:
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [ ]:
#filling the values of missing values(NaN)
sales_q1.add(sales_q2,fill_value=0)
#any ntime you do numeric operation the values change to floating data points.
#you notice the oririginal data was integers
# The fill_value fills missing values in both Series, not just one.
#It's useful for index-wise operations when the two Series have different indexes.

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [318]:
#check dat type
sales_q1.dtype

dtype('int64')

In [319]:
first_half = sales_q1.add(sales_q2,fill_value=0)

In [320]:
first_half.dtype

dtype('float64')

In [ ]:
#In Pandas (and NumPy, which it’s built on), types like int64, float64, etc.,
#  represent the data types of the values stored in your Series or DataFrame.
#int64 – 64-bit Integer
#Stands for: 64-bit signed integer

#Can store whole numbers, both positive and negative

#Range: from −2⁶³ to 2⁶³−1

#That’s from about −9.2 quintillion to +9.2 quintillion

#Used when your data has only integers (e.g., counts, IDs, etc.)
 #float64 – 64-bit Floating Point Number
#Stands for: 64-bit floating point number

#Can store decimal numbers (e.g., 3.14, 2.0, -0.5)

#Allows very large and very small real numbers, including fractional ones

#Used when your data has decimals or results of calculations like division

#Other Common Data Types
#✅ object
#General type for any kind of Python object

#Usually used for strings, like names or categories (e.g., 'Kenya', 'Red')

#But it can also include mixed types, which is less efficient

#✅ bool
#Stores Boolean values: True or False

#Often used in logical conditions or filters

#✅ datetime64[ns]
#Special data type for date and time

#The [ns] means nanosecond precision

#Useful when working with time series, timestamps, or dates
#Summary Table
#Data Type	Meaning	Example Values
#int64	64-bit integer	1, 500, -200
#float64	64-bit floating point (decimal)	3.14, -0.001, 2.0
#object	Python object (usually strings)	'Nairobi', 'A001'
#bool	Boolean	True, False
#datetime64[ns]	Timestamp with nanosecond precision	2025-06-24 08:00:00

#You can check the data types of a DataFrame using:



*

## DataFrames secion##

In [ ]:
#DataFrame is a table columns and rows in pandas that we caesily restructure and filter
#FORMAL DEFINITION~ A group of pandas series objects that share the same index
#DataFrame-several series thatb have to share same index
#each individual column is a pandas series but they(columns) allshare same index in a table
#DF is the main pandas object we will work with and it is extremely useful


In [329]:
#how to create a df from python objects
#or how to read a csv file from a data frame
#how to create;
np.random.seed(101)
mydata = np.random.randint(0,101,(4,3))

#✅ Why 2D?(The matrix formed above is 2D because);
#A 1D array looks like: [95, 11, 81] — just a simple list of values.

#A 2D array is a list of lists: each inner list is a row.

#It has both:

#an axis 0 (rows)

#and an axis 1 (columns)

#So this array has shape:
#(4, 3)
#Meaning 4 rows and 3 columns → hence, two dimensions.


#🔷 1. 3D Array
#A 3D array is like a stack of 2D matrices.

#Example:

#arr_3d = np.array([
   # [[1, 2, 3], [4, 5, 6]],       # Matrix 1 (2 rows × 3 cols)
    #[[7, 8, 9], [10, 11, 12]]     # Matrix 2 (2 rows × 3 cols)])
#print(arr_3d.shape)  # Output: (2, 2, 3)
#print(arr_3d.ndim)   # Output: 3
#Breakdown:
#2 blocks (or matrices) → axis 0

#Each block has 2 rows → axis 1

#Each row has 3 columns → axis 2

#📌 Think of it like:
#📦 A box (3D) with shape: 2 matrices × 2 rows × 3 columns
#[ [ [1, 2, 3],
  #  [4, 5, 6] ],

  #[ [7, 8, 9],
    #[10, 11, 12] ]]
#🔶 2. 4D Array
#A 4D array is a collection of 3D arrays — think of it like multiple cubes in a row.

#Example:
#arr_4d = np.array([ [   
# 3D block 1
 #       [[1, 2], [3, 4]],
#        [[5, 6], [7, 8]]
# ],
 #   [   # 3D block 2
 #       [[9, 10], [11, 12]],
   #     [[13, 14], [15, 16]]]])

#print(arr_4d.shape)  # Output: (2, 2, 2, 2)
#print(arr_4d.ndim)   # Output: 4
#Breakdown:
#2 3D blocks → axis 0

#Each block has 2 matrices → axis 1

#Each matrix has 2 rows → axis 2

#Each row has 2 columns → axis 3

#📦 Imagine:
#→ 2 Cubes → each with 2 matrices → each matrix has 2 rows × 2 cols

#🧠 Summary Table
#Dimension	Meaning	Shape Example
#1D	Vector	(4,)
#2D	Matrix	(3, 4)
#3D	Stack of Matrices	(2, 3, 4)
#4D	Collection of Matrix Stacks	(2, 2, 3, 4)



In [323]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]], dtype=int32)